version: 0.2

phases:
  install:
    commands:
      - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
      - echo GOPATH - $GOPATH
      - echo GOROOT - $GOROOT
  build:
    commands:
      - echo Build started on `date`
      - echo Getting packages
      - go get ./...
      - echo Compiling the Go code...
      - GOOS=linux GOARCH=amd64 go build -o mlldap main.go
      - GOOS=windows GOARCH=amd64 go build -o mlldap-win.exe
      - GOOS=darwin GOARCH=amd64 go build -o mlldap-mac.bin
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - mlldap
    - mlldap-win.exe
    - mlldap-mac.bin

